name: BrainsCustoms
version: '${project.version}'
main: me.brainsskel.brainscustoms.BrainsCustoms
api-version: '1.21'
authors: [BrainSkel]
description: Plugin for brains random shit
commands:
  CustomsNameplate:
    description: Set nameplate
    usage: /Customs Nameplate <player>
    permission: brainscustoms.enableNameplate
  CustomsClearNameplates:
    description: Clear all text displays
    usage: /Customs ClearNameplates
    permission: brainscustoms.ClearNameplates
  CustomsReload:
    description: Reloads BrainsCustoms plugin
    usage: /Customs Reload
    permission: brainscustoms.reload
  CustomsNameplateReload:
    description: Reload certain players nameplate
    usage: /Customs Nameplate Reload <player>